### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by leissicl** [M-Alekseev/darknet-yolo#2]
Hi, Could you please share your file of weights created?. Thanks.

**Comment by m-alekseev** [comment]
Are you still interested in it?

**Comment by leissicl** [comment]
Yes, please!. Do you still have them?

**Comment by m-alekseev** [comment]
Yep. Those are the best I had.
https://www.dropbox.com/s/kh1nfra9jajnvhi/yolo-ped_500_best.weights?dl=0

**Comment by leissicl** [comment]
Thanks! :)

**Comment by m-alekseev** [comment]
You're welcome
